# Generated by Django 2.1.3 on 2018-11-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeanApp', '0002_auto_20181122_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[('M', 'MALE'), ('F', 'FEMALE')], null=True),
        ),
    ]
