# Generated by Django 2.1.3 on 2018-11-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeanApp', '0003_auto_20181122_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=30, null=True),
        ),
    ]
