# Generated by Django 2.1.3 on 2018-11-23 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeanApp', '0006_auto_20181123_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFreeTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('student_capacity', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeanApp.Person')),
            ],
        ),
    ]
