# Generated by Django 2.1.3 on 2018-11-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeanApp', '0007_teacherfreetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/food_pics/'),
        ),
    ]
